# Generated by Django 5.2.6 on 2025-09-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_dailystats'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='words_played_today',
            field=models.IntegerField(default=0),
        ),
    ]
