# Generated by Django 5.2.6 on 2025-09-20 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_customuser_words_played_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_puzzle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_solvers', to='game.wordlist'),
        ),
    ]
